idf_component_register(SRCS "app_main.c"
                            "system_info.c"
                            "settings.c"
                            "device_params.c"
                            "factory.c"
                            "light_control/hardware/ledc_init.c"
                            "light_control/hardware/touch_button.c"
                            "light_control/button_manager.c"
                            "light_control/light_manager.c"
                            "light_control/light_control.c"
                            "Iot/mqtt_manmager.c"
                            "Iot/protocol.c"
                            "Iot/protocol_parse.c"
                            "Iot/sntp_service.c"
                            "Iot/ota.c"
                            "Iot/device_param_handler.c"
                            "Iot/param_handler.c"
                            "light_control/light_param_handler.c"
                            "sensor_control/sensor_param_handler.c"
                            "sensor_control/hardware/pir_init.c"
                            "sensor_control/hardware/bh1750.c"
                            "sensor_control/sensor_control.c"
                            "sensor_control/constant_light_control.c"
                            "Audio/mp3_player.c"
                            "Audio/audio_queue.c"
                            "Audio/audio_update.c"
                            "Audio/a2dp_sink.c"
                            "Audio/audio_mode.c"
                    INCLUDE_DIRS "."
                                 "light_control/hardware/"
                                 "light_control/"
                                 "Iot/"
                                 "sensor_control/hardware/"
                                 "sensor_control/"
                                 "Audio/"
                    )

# 创建SPIFFS分区镜像,包含音频文件
spiffs_create_partition_image(audio ../Audio_files FLASH_IN_PROJECT)

